// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace FileExchange.Controllers
{
    public partial class FileController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected FileController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditUserFile()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditUserFile);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteUserFile()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteUserFile);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ViewCategoryFiles()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ViewCategoryFiles);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ViewFile()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ViewFile);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ViewFileComments()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ViewFileComments);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddComment()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddComment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual FileExchange.Infrastructure.ActionResults.BandwidthThrottlingFileResult DownloadFile()
        {
            return new T4MVC_FileExchange_Infrastructure_ActionResults_BandwidthThrottlingFileResult(Area, Name, ActionNames.DownloadFile);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult SubscribeFileNotification()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SubscribeFileNotification);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult UnscribeFileNotification()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.UnscribeFileNotification);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult ViewCategoryFilesTableFilter()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ViewCategoryFilesTableFilter);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult UserFilesTableFilter()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.UserFilesTableFilter);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public FileController Actions { get { return MVC.File; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "File";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "File";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string FileSections = "FileSections";
            public readonly string UserFiles = "UserFiles";
            public readonly string AddUserFile = "AddUserFile";
            public readonly string EditUserFile = "EditUserFile";
            public readonly string DeleteUserFile = "DeleteUserFile";
            public readonly string ViewCategoryFiles = "ViewCategoryFiles";
            public readonly string ViewFile = "ViewFile";
            public readonly string ViewFileComments = "ViewFileComments";
            public readonly string AddComment = "AddComment";
            public readonly string DownloadFile = "DownloadFile";
            public readonly string SubscribeFileNotification = "SubscribeFileNotification";
            public readonly string UnscribeFileNotification = "UnscribeFileNotification";
            public readonly string ViewCategoryFilesTableFilter = "ViewCategoryFilesTableFilter";
            public readonly string UserFilesTableFilter = "UserFilesTableFilter";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string FileSections = "FileSections";
            public const string UserFiles = "UserFiles";
            public const string AddUserFile = "AddUserFile";
            public const string EditUserFile = "EditUserFile";
            public const string DeleteUserFile = "DeleteUserFile";
            public const string ViewCategoryFiles = "ViewCategoryFiles";
            public const string ViewFile = "ViewFile";
            public const string ViewFileComments = "ViewFileComments";
            public const string AddComment = "AddComment";
            public const string DownloadFile = "DownloadFile";
            public const string SubscribeFileNotification = "SubscribeFileNotification";
            public const string UnscribeFileNotification = "UnscribeFileNotification";
            public const string ViewCategoryFilesTableFilter = "ViewCategoryFilesTableFilter";
            public const string UserFilesTableFilter = "UserFilesTableFilter";
        }


        static readonly ActionParamsClass_AddUserFile s_params_AddUserFile = new ActionParamsClass_AddUserFile();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddUserFile AddUserFileParams { get { return s_params_AddUserFile; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddUserFile
        {
            public readonly string userFile = "userFile";
        }
        static readonly ActionParamsClass_EditUserFile s_params_EditUserFile = new ActionParamsClass_EditUserFile();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditUserFile EditUserFileParams { get { return s_params_EditUserFile; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditUserFile
        {
            public readonly string fileId = "fileId";
            public readonly string userFile = "userFile";
        }
        static readonly ActionParamsClass_DeleteUserFile s_params_DeleteUserFile = new ActionParamsClass_DeleteUserFile();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteUserFile DeleteUserFileParams { get { return s_params_DeleteUserFile; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteUserFile
        {
            public readonly string fileId = "fileId";
        }
        static readonly ActionParamsClass_ViewCategoryFiles s_params_ViewCategoryFiles = new ActionParamsClass_ViewCategoryFiles();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ViewCategoryFiles ViewCategoryFilesParams { get { return s_params_ViewCategoryFiles; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ViewCategoryFiles
        {
            public readonly string categoryId = "categoryId";
        }
        static readonly ActionParamsClass_ViewFile s_params_ViewFile = new ActionParamsClass_ViewFile();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ViewFile ViewFileParams { get { return s_params_ViewFile; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ViewFile
        {
            public readonly string fileId = "fileId";
        }
        static readonly ActionParamsClass_ViewFileComments s_params_ViewFileComments = new ActionParamsClass_ViewFileComments();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ViewFileComments ViewFileCommentsParams { get { return s_params_ViewFileComments; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ViewFileComments
        {
            public readonly string fileId = "fileId";
        }
        static readonly ActionParamsClass_AddComment s_params_AddComment = new ActionParamsClass_AddComment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddComment AddCommentParams { get { return s_params_AddComment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddComment
        {
            public readonly string fileId = "fileId";
            public readonly string commentModel = "commentModel";
        }
        static readonly ActionParamsClass_DownloadFile s_params_DownloadFile = new ActionParamsClass_DownloadFile();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DownloadFile DownloadFileParams { get { return s_params_DownloadFile; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DownloadFile
        {
            public readonly string fileId = "fileId";
        }
        static readonly ActionParamsClass_SubscribeFileNotification s_params_SubscribeFileNotification = new ActionParamsClass_SubscribeFileNotification();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SubscribeFileNotification SubscribeFileNotificationParams { get { return s_params_SubscribeFileNotification; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SubscribeFileNotification
        {
            public readonly string fileId = "fileId";
        }
        static readonly ActionParamsClass_UnscribeFileNotification s_params_UnscribeFileNotification = new ActionParamsClass_UnscribeFileNotification();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UnscribeFileNotification UnscribeFileNotificationParams { get { return s_params_UnscribeFileNotification; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UnscribeFileNotification
        {
            public readonly string fileId = "fileId";
        }
        static readonly ActionParamsClass_ViewCategoryFilesTableFilter s_params_ViewCategoryFilesTableFilter = new ActionParamsClass_ViewCategoryFilesTableFilter();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ViewCategoryFilesTableFilter ViewCategoryFilesTableFilterParams { get { return s_params_ViewCategoryFilesTableFilter; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ViewCategoryFilesTableFilter
        {
            public readonly string param = "param";
        }
        static readonly ActionParamsClass_UserFilesTableFilter s_params_UserFilesTableFilter = new ActionParamsClass_UserFilesTableFilter();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UserFilesTableFilter UserFilesTableFilterParams { get { return s_params_UserFilesTableFilter; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UserFilesTableFilter
        {
            public readonly string param = "param";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _CreateComment = "_CreateComment";
                public readonly string _FileSections = "_FileSections";
                public readonly string _fileSubscribe = "_fileSubscribe";
                public readonly string _ViewFileComments = "_ViewFileComments";
                public readonly string AddUserFile = "AddUserFile";
                public readonly string EditUserFile = "EditUserFile";
                public readonly string UserFiles = "UserFiles";
                public readonly string ViewCategoryFiles = "ViewCategoryFiles";
                public readonly string ViewFile = "ViewFile";
            }
            public readonly string _CreateComment = "~/Views/File/_CreateComment.cshtml";
            public readonly string _FileSections = "~/Views/File/_FileSections.cshtml";
            public readonly string _fileSubscribe = "~/Views/File/_fileSubscribe.cshtml";
            public readonly string _ViewFileComments = "~/Views/File/_ViewFileComments.cshtml";
            public readonly string AddUserFile = "~/Views/File/AddUserFile.cshtml";
            public readonly string EditUserFile = "~/Views/File/EditUserFile.cshtml";
            public readonly string UserFiles = "~/Views/File/UserFiles.cshtml";
            public readonly string ViewCategoryFiles = "~/Views/File/ViewCategoryFiles.cshtml";
            public readonly string ViewFile = "~/Views/File/ViewFile.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_FileController : FileExchange.Controllers.FileController
    {
        public T4MVC_FileController() : base(Dummy.Instance) { }

        [NonAction]
        partial void FileSectionsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult FileSections()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.FileSections);
            FileSectionsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void UserFilesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult UserFiles()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UserFiles);
            UserFilesOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void AddUserFileOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddUserFile()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddUserFile);
            AddUserFileOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void AddUserFileOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, FileExchange.Models.CreateExchangeFileModel userFile);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddUserFile(FileExchange.Models.CreateExchangeFileModel userFile)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddUserFile);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userFile", userFile);
            AddUserFileOverride(callInfo, userFile);
            return callInfo;
        }

        [NonAction]
        partial void EditUserFileOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int fileId);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditUserFile(int fileId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditUserFile);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "fileId", fileId);
            EditUserFileOverride(callInfo, fileId);
            return callInfo;
        }

        [NonAction]
        partial void EditUserFileOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, FileExchange.Models.EditExchangeFileModel userFile);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditUserFile(FileExchange.Models.EditExchangeFileModel userFile)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditUserFile);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "userFile", userFile);
            EditUserFileOverride(callInfo, userFile);
            return callInfo;
        }

        [NonAction]
        partial void DeleteUserFileOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int fileId);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteUserFile(int fileId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteUserFile);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "fileId", fileId);
            DeleteUserFileOverride(callInfo, fileId);
            return callInfo;
        }

        [NonAction]
        partial void ViewCategoryFilesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int categoryId);

        [NonAction]
        public override System.Web.Mvc.ActionResult ViewCategoryFiles(int categoryId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ViewCategoryFiles);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "categoryId", categoryId);
            ViewCategoryFilesOverride(callInfo, categoryId);
            return callInfo;
        }

        [NonAction]
        partial void ViewFileOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int fileId);

        [NonAction]
        public override System.Web.Mvc.ActionResult ViewFile(int fileId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ViewFile);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "fileId", fileId);
            ViewFileOverride(callInfo, fileId);
            return callInfo;
        }

        [NonAction]
        partial void ViewFileCommentsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int fileId);

        [NonAction]
        public override System.Web.Mvc.ActionResult ViewFileComments(int fileId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ViewFileComments);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "fileId", fileId);
            ViewFileCommentsOverride(callInfo, fileId);
            return callInfo;
        }

        [NonAction]
        partial void AddCommentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int fileId);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddComment(int fileId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddComment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "fileId", fileId);
            AddCommentOverride(callInfo, fileId);
            return callInfo;
        }

        [NonAction]
        partial void AddCommentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, FileExchange.Models.CreateCommentViewModel commentModel);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddComment(FileExchange.Models.CreateCommentViewModel commentModel)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddComment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "commentModel", commentModel);
            AddCommentOverride(callInfo, commentModel);
            return callInfo;
        }

        [NonAction]
        partial void DownloadFileOverride(T4MVC_FileExchange_Infrastructure_ActionResults_BandwidthThrottlingFileResult callInfo, int fileId);

        [NonAction]
        public override FileExchange.Infrastructure.ActionResults.BandwidthThrottlingFileResult DownloadFile(int fileId)
        {
            var callInfo = new T4MVC_FileExchange_Infrastructure_ActionResults_BandwidthThrottlingFileResult(Area, Name, ActionNames.DownloadFile);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "fileId", fileId);
            DownloadFileOverride(callInfo, fileId);
            return callInfo;
        }

        [NonAction]
        partial void SubscribeFileNotificationOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int fileId);

        [NonAction]
        public override System.Web.Mvc.JsonResult SubscribeFileNotification(int fileId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SubscribeFileNotification);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "fileId", fileId);
            SubscribeFileNotificationOverride(callInfo, fileId);
            return callInfo;
        }

        [NonAction]
        partial void UnscribeFileNotificationOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int fileId);

        [NonAction]
        public override System.Web.Mvc.JsonResult UnscribeFileNotification(int fileId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.UnscribeFileNotification);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "fileId", fileId);
            UnscribeFileNotificationOverride(callInfo, fileId);
            return callInfo;
        }

        [NonAction]
        partial void ViewCategoryFilesTableFilterOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, FileExchange.Models.DataTable.DefaultDataTablesRequest param);

        [NonAction]
        public override System.Web.Mvc.JsonResult ViewCategoryFilesTableFilter(FileExchange.Models.DataTable.DefaultDataTablesRequest param)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ViewCategoryFilesTableFilter);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "param", param);
            ViewCategoryFilesTableFilterOverride(callInfo, param);
            return callInfo;
        }

        [NonAction]
        partial void UserFilesTableFilterOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, FileExchange.Models.JQueryDataTablesModel param);

        [NonAction]
        public override System.Web.Mvc.JsonResult UserFilesTableFilter(FileExchange.Models.JQueryDataTablesModel param)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.UserFilesTableFilter);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "param", param);
            UserFilesTableFilterOverride(callInfo, param);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
